version: "3"
services:
  coordinator:
    image: nebulastream/nes-executable-image:local
    entrypoint: ["bash", "-c", "nesCoordinator --configPath=/tutorial/coordinator.yml"]
    ports:
      - 8081:8081
    volumes:
      - ./:/tutorial
    networks:
      nebulastream-network:
        ipv4_address: 172.31.0.2
  worker:
    image: nebulastream/nes-executable-image:local
    entrypoint: ["bash", "-c", "sleep 3 && nesWorker --configPath=/tutorial/worker-1.yml"]
    volumes:
      - ./:/tutorial
    networks:
      nebulastream-network:
        ipv4_address: 172.31.0.3
  ui:
    image: nebulastream/nes-ui-image:latest
    ports:
      - 9000:9000
    networks:
      nebulastream-network:
        ipv4_address: 172.31.0.12
  tcp_source:
    image: nes-tuple-source:latest
    ports:
      - 8081:8081
    networks:
      nebulastream-network:
        ipv4_address: 172.31.0.99
networks:
  nebulastream-network:
    ipam:
      config:
        - subnet: 172.31.0.0/24
